# Specify the model to use for the main chat
model: sonnet

# Enable/disable adding .aider* to .gitignore (default: True)
gitignore: false

# Enable/disable watching files for ai coding comments (default: False)
watch-files: true

# Enable/disable automatic linting after changes (default: True)
auto-lint: false

# Always say yes to every confirmation (default: False)
yes-always: false
